context:
  version: "0.15.1"

package:
  name: typstyle
  version: ${{ version }}

source:
  url: https://github.com/typstyle-rs/typstyle/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0f1b86584a0eb93b0cef374ddcc62508c46ee76cd8b5ede31414260d29a38f12

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cd crates/typstyle
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - typstyle --version
      - typstyle --help
  - package_contents:
      bin:
        - typstyle
      strict: true

about:
  homepage: https://github.com/typstyle-rs/typstyle
  repository: https://github.com/typstyle-rs/typstyle
  documentation: https://typstyle-rs.github.io/typstyle/
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Beautiful and reliable typst code formatter

extra:
  recipe-maintainers:
    - pavelzw
